
services:
  db:
    image: docker.io/library/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --log-bin=binlog --expire_logs_days=3 --secure-file-priv=""
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE, fix error mbind: Operation not permitted
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=mediawiki
    secrets:
      - db_root_password
    volumes:
      - ./_initdb:/docker-entrypoint-initdb.d
      - ./_data/mysql:/var/lib/mysql

  web:
    image: ghcr.io/canastawiki/canasta:wikiteq-985789c0 # 1.39.8
    restart: unless-stopped
    extra_hosts:
      - "gateway.docker.internal:host-gateway"
    depends_on:
      - db
      - elasticsearch
    environment:
      # Sourced from .env
      - MW_SITE_SERVER=${MW_SITE_SERVER?Variable MW_SITE_SERVER not set}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_POST_MAX_SIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-1000}
      - MW_ENABLE_SITEMAP_GENERATOR # Enable it on the PROD wiki only! See WIK-1420
      - PASSWORD_SENDER=eyewiki@aao.org
      - MW_SITE_FQDN
      - APACHE_REMOTE_IP_HEADER=X-Real-Ip # Use IP passed by Traefik, see MEYE-401
    secrets:
      - db_root_password
      - google_key
      - smtp_password
      - wgSentryDsn
    volumes:
      - ./_data/mediawiki:/mediawiki
      - ./extensions:/var/www/mediawiki/w/user-extensions
      - ./skins:/var/www/mediawiki/w/user-skins
      - ./config:/mediawiki/config
      - ./images:/mediawiki/images

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms${ES_MEMORY:-512m} -Xmx${ES_MEMORY:-512m}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  varnish:
    image: pastakhov/varnish:7.0
    restart: unless-stopped
    networks:
      - traefik-public
      - default
    depends_on:
      - web
    environment:
      - VARNISH_SIZE=${VARNISH_SIZE:-1g}
      - VARNISH_STORAGE_KIND=file
    volumes:
       - ./config/varnish:/etc/varnish:ro
       - ./_data/varnish:/data
    tmpfs:
      - /var/lib/varnish:exec
    labels:
      # Enable Traefik for this service
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      # Set the domain name for the service
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-varnish.rule=Host(`${MW_SITE_FQDN?Variable MW_SITE_FQDN not set}`)
      # Set http and https entrypoints for the service
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-varnish.entrypoints=websecure
      # Connect the service to LE certs resolver
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-varnish.tls.certresolver=le
      # Redirect www subdomain to base
      # HTTPS
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-websecure.rule=Host(`www.$MW_SITE_FQDN`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-websecure.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-websecure.tls.certresolver=le
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-websecure.middlewares=${COMPOSE_PROJECT_NAME}_www_redirect
      # HTTP
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-web.rule=Host(`www.$MW_SITE_FQDN`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-web.entrypoints=web
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-web.middlewares=${COMPOSE_PROJECT_NAME}_www_redirect
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-www-web.priority=100
      # the redirect middleware
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_www_redirect.redirectregex.regex=^https?://www\.(.*)
      - traefik.http.middlewares.${COMPOSE_PROJECT_NAME}_www_redirect.redirectregex.replacement=https://$${1}

  # https://hub.docker.com/_/composer
  massmessage:
    image: composer:2.2
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./eyewiki-massmessage-apiscripts:/app
    command: "sleep infinity"
    environment:
      # Sourced from .env
      - MASSMESSAGE_LIVE_MODE # Set true on production
      - MASSMESSAGE_SITE_URL=http://web/w
      - MASSMESSAGE_BOT_USER
      - MASSMESSAGE_BOT_PASSWORD_FILE=/run/secrets/massmessage_bot_password
      - MASSMESSAGE_SPAMLIST_CATEGORY
    secrets:
      - massmessage_bot_password
    labels:
      # At 11:00 every first Friday
      cron.massmessage.schedule: "0 11 * * FRI#1"
      cron.massmessage.command: "bash run.sh MassMessageAPI.php"
      # At 11:00 every day
      cron.stalepages.schedule: "0 11 * * *"
      cron.stalepages.command: "bash run.sh stalepages.php"

  # it uses "Golang Cron expression parser", see https://github.com/aptible/supercronic/tree/master/cronexpr
  cron:
    image: ghcr.io/wikiteq/cron:20241025-6
    environment:
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - DEBUG=${CRON_DEBUG:-0}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/cron:/var/log/cron

restic:
    image: ghcr.io/wikiteq/restic-backup-docker:stream
    restart: unless-stopped
    depends_on:
        - db
    environment:
        - MW_DB_USER=root
        - MW_DB_PASS_FILE=/run/secrets/db_root_password
        - MW_DB_NAME=$MW_DB_NAME
        - RESTIC_TAG=backup_full
        - BACKUP_CRON=0 1 * * 6
        - CHECK_CRON=0 23 * * 5
        - RESTIC_FORGET_ARGS=--prune --keep-weekly 1 --keep-monthly 2 --group-by paths
        # pre-backup script
        - RESTIC_PRE_BACKUP=if [ ! -d "/data" ]; then mkdir /data; fi && mysqldump -hdb -u$$MW_DB_USER -p$$MW_DB_PASS $$MW_DB_NAME | gzip -c > /data/database.sql.gz
        # post-backup script
        - RESTIC_POST_BACKUP=rm /data/database.sql.gz
        - RESTIC_STREAM=yes
        - RESTIC_STREAM_CMD=tar -cf - -C /data_mediawiki/ /data/database.sql.gz images
        - RESTIC_STREAM_FILENAME=full.images.database.tar
        - RESTIC_REPOSITORY_FILE=/run/secrets/restic_s3_repository
        - RESTIC_PASSWORD_FILE=/run/secrets/restic_password
        - AWS_SHARED_CREDENTIALS_FILE=/run/secrets/aws_credentials
    secrets:
        - aws_credentials
        - db_root_password
        - restic_password
        - restic_s3_repository
    volumes:
        - ./_data/mediawiki:/data_mediawiki:ro
        - ./_logs/restic:/var/log

secrets:
  aws_credentials:
    file: ./secrets/aws_credentials.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  google_key:
    file: ./secrets/google-key.json
  massmessage_bot_password:
    file: ./secrets/massmessage_bot_password.txt
  restic_password:
    file: ./secrets/restic_password.txt
  restic_s3_repository:
    file: ./secrets/restic_s3_repository.txt
  smtp_password:
    file: ./secrets/smtp_password.txt
  wgSentryDsn:
    file: ./secrets/wgSentryDsn.txt

volumes:
  elasticsearch:

networks:
  traefik-public:
    external: true
