version: '3.7'
services:
  db:
    image: docker.io/library/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --log-bin=binlog --expire_logs_days=3 --secure-file-priv=""
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE, fix error mbind: Operation not permitted
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-mediawiki}
      - MYSQL_DATABASE=mediawiki
    volumes:
      - ./_initdb:/docker-entrypoint-initdb.d
      - ./_data/mysql:/var/lib/mysql

  web:
    image: ghcr.io/canastawiki/canasta:wikiteq-5824f75e
    restart: unless-stopped
    links:
      - db
      - elasticsearch
    extra_hosts:
      - "gateway.docker.internal:host-gateway"
    depends_on:
      - db
      - elasticsearch
    environment:
      # Sourced from .env
      - MW_SITE_SERVER=${MW_SITE_SERVER:-http://localhost}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_POST_MAX_SIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-1000}
      - MW_ENABLE_SITEMAP_GENERATOR # Enable it on the PROD wiki only! See WIK-1420
      - MW_SITEMAP_SUBDIR
      - MW_SITEMAP_IDENTIFIER
      - MW_SENTRY_DSN
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - PASSWORD_SENDER
    volumes:
      - ./extensions:/var/www/mediawiki/w/user-extensions
      - ./skins:/var/www/mediawiki/w/user-skins
      - ./config:/mediawiki/config
      - ./images:/mediawiki/images
      - ./eyewiki-google-key.json:/var/www/eyewiki-1036-4bd0970ee9af.json
      - sitemap:/mediawiki/sitemap

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  caddy:
    image: docker.io/library/caddy:2.4.6-alpine
    restart: unless-stopped
    links:
      - varnish
    entrypoint: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    environment:
      - MW_SITE_FQDN=${MW_SITE_FQDN:-localhost}
    ports:
      - "${PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - caddy-data:/data
      - ./config/Caddyfile:/etc/caddy/Caddyfile

  varnish:
    image: pastakhov/varnish:7.0
    restart: unless-stopped
    links:
      - web
    environment:
      - VARNISH_SIZE=${VARNISH_SIZE:-1g}
      - VARNISH_STORAGE_KIND=file
    volumes:
       - ./config/varnish:/etc/varnish:ro
       - ./_data/varnish:/data
    tmpfs:
      - /var/lib/varnish:exec

  # https://hub.docker.com/_/composer
  massmessage:
    image: composer:2.2
    restart: unless-stopped
    volumes:
      - ./eyewiki-massmessage-apiscripts:/app
    command: "sleep infinity"
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.massmessage.schedule: "@every 30m"
      #ofelia.job-exec.massmessage.schedule: "0 11 1-7 * *"
      ofelia.job-exec.massmessage.command: "bash run.sh"
      ofelia.job-exec.massmessage.no-overlap: true

  # https://github.com/mcuadros/ofelia
  ofelia:
    image: mcuadros/ofelia:39bca16
    links:
      - massmessage
    depends_on:
      - massmessage
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs/ofelia:/var/log/ofelia
    labels:
      ofelia.enabled: "true"
      ofelia.save-folder: "/var/log/ofelia"
      ofelia.save-only-on-error: false

volumes:
  elasticsearch:
  caddy-data:
  sitemap:
