<?php
// error_reporting( E_ALL | E_STRICT );
// ini_set( "display_errors", 1 );
// $wgShowExceptionDetails = true;
// $wgShowSQLErrors = true;
// $wgDebugComments = true;
// $wgLogQueries = true;
// $wgDebugDumpSql = true;
// $wgDevelopmentWarnings = true;
// $wgDebugProfiling = true;
// $wgDebugTimestamps = true;
// $wgDebugPrintHttpHeaders = false;
// $wgResourceLoaderDebug = true;
// $wgEnableParserCache = false;
// $wgResourceLoaderMaxage = 1;
// $wgCachePages = false;
// $wgDebugToolbar = true;
// $wgShowDebug = true;
// $wgShowDBErrorBacktrace = true;

# This file was automatically generated by the MediaWiki 1.23.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

$wgScriptPath = "/w";
$wgScriptExtension = ".php";
$wgArticlePath = "/$1";
$wgUsePathInfo = true;

## The relative URL path to the skins directory
$wgStylePath = "$wgScriptPath/skins";

$wgDBtype = "mysql";
$wgDBprefix = "";
$wgDBserver = "db";
$wgDBname = "mediawiki";
$wgDBuser = "root";
$wgDBpassword = "mediawiki";
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL; //CACHE_NONE;
$wgMemCachedServers = [];

$wgSecretKey = "2cf482ee57877fc0508262824d9eedc17d09e48e3ce953c0e5a8adc843acd9de";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "d9316e1c812933c8";

# SemanticMediaWiki - needs to be here - called before other Semantic extensions
wfLoadExtension( 'SemanticMediaWiki' );
enableSemantics( getenv( 'MW_SITE_FQDN' ) );

require_once("$IP/extensions/EyeWiki/LocalSettings.php");

/******************* Core configuration ********************/

$wgSentryDsn = getenv( 'MW_SENTRY_DSN' );
$wgGoogleAnalyticsMetricsPath = '/var/www/eyewiki-1036-4bd0970ee9af.json';
$wgGoogleAnalyticsMetricsEmail = '406809334386-o49bi6p7qk3701pm9arvu3elfpkh7t4a@developer.gserviceaccount.com';
$wgGoogleAnalyticsMetricsViewId = '104606307';

// Temporary. This may slow things down. Maybe change to only POST later.
// MEYE-254

class MyProfilerOutput extends ProfilerOutput {
	private $thresholdMs;

	public function __construct( Profiler $collector, array $params ) {
		parent::__construct( $collector, $params );
		$this->thresholdMs = $params['thresholdMs'] ?? 20.0;
	}

	public function log( array $stats ) {
		$out = $_SERVER['REQUEST_METHOD'] . ' ' . $_SERVER['REQUEST_URI'] . "\n";

		// Filter out really tiny entries
		$min = $this->thresholdMs;
		$stats = array_filter( $stats, static function ( $a ) use ( $min ) {
			return $a['real'] > $min;
		} );
		// Sort descending by time elapsed
		usort( $stats, static function ( $a, $b ) {
			return $b['real'] <=> $a['real'];
		} );

		if ( !$stats ) {
			// Nothing below threshold.
			return;
		}
		if ( isset( $stats[0]['real'] ) && $stats[0]['real'] < 1000*9 ) {
			// only record > 9 seconds
			return;
		}
		$out .= shell_exec( 'free -h; vmstat -S M; echo; ps aux --sort -%cpu | head; echo ---- ; ps aux --sort -%mem | head' ) . "\n";
		array_walk( $stats,
			static function ( $item ) use ( &$out ) {
				$out .= sprintf( "%6.2f%% %3.3f %6d - %s\n",
					$item['%real'], $item['real'], $item['calls'], $item['name'] );
			}
		);
		global $wgTitle;
		$filename = sprintf( "%s/%s.%s.%s.txt",
			'/var/log/mediawiki/profiles',
			wfTimestampNow( TS_MW ),
			uniqid(),
			str_replace( "/", "-", $wgTitle ? $wgTitle->getPrefixedDBKey() : 'UNKNOWN' )
		);
		file_put_contents( $filename, $out );
	}


}

//$wgProfiler['class'] = 'ProfilerXhprof';
//$wgProfiler['output'] = [ 'MyProfilerOutput' ];

// MEYE-254
$wgCacheDirectory = __DIR__ . '/cache';
$wgLocalisationCacheConf['store'] = 'array';

// We have a separate job runner.
$wgJobRunRate = 0;

wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SemanticScribunto' );
